### PR TITLE
Fix build. Upgrade to Gradle 5.6. Coverage report at coveralls

### PR DESCRIPTION
**Pull request by crc83**

### CODE REVIEW

**Comment by ghale** [comment]
Thanks for the PR @crc83!  I've left a number of comments on this.  I think the main things that need to be fixed before we can consider merging this are:

- Fix merge conflicts
- Re-enable integ tests
- Fix all of the instances of terrafolio -> sbelei
- Remove the duplication in `src/main/java`

@www44 Would love to get your eyes on this, too.

**Comment by www44** [comment]
hi,

sure, tomorrow

BR
Vladi

Am So., 25. Aug. 2019 um 18:07 Uhr schrieb Gary Hale <
notifications@github.com>:

**Comment by www44** [comment]
for me, it looks like wrong target branch for git push because of Gradle plugin id update

@crc83 : if it so, please take a decision what do you want, if you want to update terrafolio plugin, please do this accordingly (take care about tests, not add additional secrets, etc) or create your own version with new gradle plugin id.

**Comment by crc83** [comment]
It's my fault. I made pull request in wrong repo. I'm maintaining my own fork for two years. 
No reason for me to put efforts in integration right now.

**Pull request closed without merging**
